# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-24 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='observaciones',
            field=models.TextField(null=True),
        ),
    ]
