# Generated by Django 3.0.4 on 2020-03-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendador', '0002_auto_20200324_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='precio',
            field=models.FloatField(),
        ),
    ]
