# Generated by Django 3.0.4 on 2020-03-31 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendador', '0003_auto_20200325_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acertado',
            name='producto',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='architecture',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='batman',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='city',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='friends',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='minecraft',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nPiezas',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(),
        ),
    ]
